//
// Created by jasf on 4/1/16.
//

#ifndef IDJ201601T1_DEFINES_H
#define IDJ201601T1_DEFINES_H

#import <SDL_keycode.h>

#define LEFT_ARROW_KEY SDLK_LEFT
#define RIGHT_ARROW_KEY SDLK_RIGHT
#define UP_ARROW_KEY SDLK_UP
#define DOWN_ARROW_KEY SDLK_DOWN
#define ESCAPE_KEY SDLK_ESCAPE
#define LEFT_MOUSE_BUTTON SDL_BUTTON_LEFT

#endif //IDJ201601T1_DEFINES_H
