#ifndef DEFINESHPP
#define DEFINESHPP

#include <SDL.H>

#define INPUT_MANAGER_MOUSE_STATE_SIZE 6
#define LEFT_ARROW_KEY SDLK_LEFT
#define RIGHT_ARROW_KEY SDLK_RIGHT
#define UP_ARROW_KEY SDLK_UP
#define DOWN_ARROW_KEY SDLK_DOWN
#define ESCAPE_KEY SDLK_ESCAPE
#define LEFT_MOUSE_BUTTON SDL_BUTTON_LEFT
#define RIGHT_MOUSE_BUTTON SDL_BUTTON_RIGHT

#define KEY_LOW_CASE_W SDLK_w
#define KEY_LOW_CASE_S SDLK_s
#define KEY_LOW_CASE_A SDLK_a
#define KEY_LOW_CASE_D SDLK_d

#define SPACE_BAR SDLK_SPACE


#endif // DEFINESHPP
